name: $bog_figmol_app

permissions: write-all

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  package: "bog/figmol"
                  modules: 'app'

            - uses: hyoo-ru/gh-deploy@v4.4.1
              if: github.ref == 'refs/heads/main'
              with:
                  folder: "bog/figmol/app/-"

