name: $bog_figmol_app

permissions: write-all

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  package: "bog/figmol"
                  modules: 'app'

            - uses: hyoo-ru/gh-deploy@v4.4.1
              if: github.ref == 'refs/heads/main'
              with:
                  folder: "bog/figmol/app/-"

            - uses: actions/upload-pages-artifact@v3
              if: github.ref == 'refs/heads/main'
              with:
                  path: "bog/figmol/app/-"

    pages:
        needs: build
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - id: deployment
              uses: actions/deploy-pages@v4

